"""Initial Migration

Revision ID: 11c3f9787c5b
Revises: c29ae98ceb70
Create Date: 2019-02-28 08:17:17.537919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c3f9787c5b'
down_revision = 'c29ae98ceb70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('upvote', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'upvote')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'downvote')
    # ### end Alembic commands ###
